services:
  - type: web
    name: boxway-moviecloud-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    rootDir: my-react-app
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
